### ISSUE TITLE
Notinstalling because of an issue with pillow installation which i already installed

### ISSUE THREAD

**Issue by Whizfactor** [WimpyAnalytics/django-andablog#69]
pip install django-andablog
Collecting django-andablog
  Using cached django_andablog-3.2.0-py2.py3-none-any.whl
Collecting pillow<8.0.0,>=4.0.0
  Using cached Pillow-7.2.0.tar.gz (39.1 MB)
  Preparing metadata (setup.py) ... done
Collecting django-model-utils<5.0,>=3.0
  Using cached django_model_utils-4.2.0-py3-none-any.whl (33 kB)
Requirement already satisfied: six in c:\users\whizf\python_money_projects\what_a_blog\env\lib\site-packages (from django-andablog) (1.16.0)
Requirement already satisfied: django-markupfield<3,>=1.5 in c:\users\whizf\python_money_projects\what_a_blog\env\lib\site-packages (from django-andablog) (2.0.1)
Collecting Django<2.3,>=2.0
  Using cached Django-2.2.28-py3-none-any.whl (7.5 MB)
Collecting django-taggit<2.0.0,>=0.22.2
  Using cached django_taggit-1.5.1-py3-none-any.whl (53 kB)
Requirement already satisfied: sqlparse>=0.2.2 in c:\users\whizf\python_money_projects\what_a_blog\env\lib\site-packages (from Django<2.3,>=2.0->django-andablog) (0.4.2)
Requirement already satisfied: pytz in c:\users\whizf\python_money_projects\what_a_blog\env\lib\site-packages (from Django<2.3,>=2.0->django-andablog) (2022.1)
Building wheels for collected packages: pillow
  Building wheel for pillow (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [176 lines of output]
      C:\Users\Whizf\AppData\Local\Temp\pip-install-h8j4hk91\pillow_202c10d83087402aa5e1d67f631a8a7f\setup.py:42: RuntimeWarning: Pillow 7.2.0 does not support Python 3.9 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-3.9\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext
     
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
      Traceback (most recent call last):
        File "C:\Users\Whizf\AppData\Local\Temp\pip-install-h8j4hk91\pillow_202c10d83087402aa5e1d67f631a8a7f\setup.py", line 864, in <module>
          setup(
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "C:\Users\Whizf\AppData\Local\Temp\pip-install-h8j4hk91\pillow_202c10d83087402aa5e1d67f631a8a7f\setup.py", line 694, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: zlib
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Whizf\AppData\Local\Temp\pip-install-h8j4hk91\pillow_202c10d83087402aa5e1d67f631a8a7f\setup.py", line 918, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
  Running setup.py clean for pillow
Failed to build pillow
Installing collected packages: pillow, Django, django-taggit, django-model-utils, django-andablog
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.1.0
    Uninstalling Pillow-9.1.0:
      Successfully uninstalled Pillow-9.1.0
  Running setup.py install for pillow ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pillow did not run successfully.
  │ exit code: 1
  ╰─> [180 lines of output]
      C:\Users\Whizf\AppData\Local\Temp\pip-install-h8j4hk91\pillow_202c10d83087402aa5e1d67f631a8a7f\setup.py:42: RuntimeWarning: Pillow 7.2.0 does not support Python 3.9 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
        warnings.warn(
      running install
      C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-3.9\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-3.9\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext
     
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
      Traceback (most recent call last):
        File "C:\Users\Whizf\AppData\Local\Temp\pip-install-h8j4hk91\pillow_202c10d83087402aa5e1d67f631a8a7f\setup.py", line 864, in <module>
          setup(
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\command\install.py", line 670, in run
          self.run_command('build')
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "C:\Users\Whizf\AppData\Local\Temp\pip-install-h8j4hk91\pillow_202c10d83087402aa5e1d67f631a8a7f\setup.py", line 694, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: zlib
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Whizf\AppData\Local\Temp\pip-install-h8j4hk91\pillow_202c10d83087402aa5e1d67f631a8a7f\setup.py", line 918, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\users\whizf\python_money_projects\what_a_blog\env\lib\site-packages
  Rolling back uninstall of pillow
  Moving to c:\users\whizf\python_money_projects\what_a_blog\env\lib\site-packages\pil\
   from C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\Lib\site-packages\~-l
  Moving to c:\users\whizf\python_money_projects\what_a_blog\env\lib\site-packages\pillow-9.1.0.dist-info\
   from C:\Users\Whizf\Python_Money_Projects\What_A_Blog\env\Lib\site-packages\~illow-9.1.0.dist-info
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Whizfactor** [comment]
I uninstalled pillow, still didnt install.
